// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type Student struct {
	Name  string `json:"name"`
	Score int    `json:"score"`
}

type StudentOverallResult struct {
	Position int             `json:"position"`
	Result   []*StudentScore `json:"result"`
}

type StudentScore struct {
	ID       string `json:"_id"`
	Name     string `json:"name"`
	Subject  string `json:"subject"`
	Score    int    `json:"score"`
	Position int    `json:"position"`
}

type StudentTotalScore struct {
	Name     string `json:"name"`
	Total    int    `json:"total"`
	Position int    `json:"position"`
}

type StudentsScoreInput struct {
	Subject  string     `json:"subject"`
	Students []*Student `json:"students"`
}

type SubjectAssessment struct {
	Subject  string          `json:"subject"`
	Students []*StudentScore `json:"students"`
}
